# Generated by Django 2.0.7 on 2019-01-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title_head',
            new_name='title',
        ),
    ]
